'use server'

import { revalidatePath } from 'next/cache'
import { getSupabaseServerClient } from '@/lib/supabase/server'
import { getSupabaseAdminClient } from '@/lib/supabase/admin'
import { resend } from '@/lib/resend/client'
import { inviteEmailHtml } from '@/lib/resend/templates/invite-email'
import { canAddMember } from '@/lib/limits'

// ─── Invite ───────────────────────────────────────────────────────────────────

export async function inviteMember(
  workspaceId: string,
  email: string,
  role: 'admin' | 'member'
): Promise<{ error?: string; inviteUrl?: string }> {
  const supabase = await getSupabaseServerClient()
  const admin = getSupabaseAdminClient()

  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return { error: 'Não autenticado' }

  // Verify caller is admin of this workspace
  const { data: membership } = await supabase
    .from('workspace_members')
    .select('role')
    .eq('workspace_id', workspaceId)
    .eq('user_id', user.id)
    .eq('status', 'active')
    .single()

  if (!membership || membership.role !== 'admin') {
    return { error: 'Apenas admins podem convidar membros.' }
  }

  // Check plan limit
  const limit = await canAddMember(workspaceId)
  if (!limit.allowed) return { error: limit.reason }

  // Check for existing pending invite for this email
  const { data: existingInvite } = await admin
    .from('workspace_invites')
    .select('id')
    .eq('workspace_id', workspaceId)
    .eq('email', email.toLowerCase().trim())
    .is('accepted_at', null)
    .gt('expires_at', new Date().toISOString())
    .maybeSingle()

  if (existingInvite) {
    return { error: 'Já existe um convite pendente para este e-mail.' }
  }

  // Create invite (token is generated by database default)
  const { data: invite, error: inviteError } = await admin
    .from('workspace_invites')
    .insert({
      workspace_id: workspaceId,
      email: email.toLowerCase().trim(),
      role,
      invited_by: user.id,
    })
    .select('token')
    .single()

  if (inviteError || !invite) {
    return { error: 'Erro ao criar convite. Tente novamente.' }
  }

  // Get workspace name for email
  const { data: workspace } = await supabase
    .from('workspaces')
    .select('name')
    .eq('id', workspaceId)
    .single()

  const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'
  const inviteUrl = `${appUrl}/invite/${invite.token}`

  // Send email via Resend
  const { error: emailError } = await resend.emails.send({
    from: process.env.RESEND_FROM_EMAIL || 'onboarding@resend.dev',
    to: email.trim(),
    subject: `Você foi convidado para ${workspace?.name ?? 'SemComplicação CRM'}`,
    html: inviteEmailHtml({
      workspaceName: workspace?.name ?? workspaceId,
      inviterEmail: user.email!,
      inviteUrl,
    }),
  })

  if (emailError) {
    // Email failed (e.g. Resend free plan restriction) — keep the invite and return the link
    revalidatePath('/settings')
    return { inviteUrl }
  }

  revalidatePath('/settings')
  return {}
}

// ─── Cancel invite ────────────────────────────────────────────────────────────

export async function cancelInvite(inviteId: string): Promise<{ error?: string }> {
  const admin = getSupabaseAdminClient()

  const { error } = await admin
    .from('workspace_invites')
    .delete()
    .eq('id', inviteId)

  if (error) return { error: 'Erro ao cancelar convite.' }

  revalidatePath('/settings')
  return {}
}

// ─── Remove member ────────────────────────────────────────────────────────────

export async function removeMember(
  memberId: string,
  currentUserId: string
): Promise<{ error?: string }> {
  const admin = getSupabaseAdminClient()

  const { data: target } = await admin
    .from('workspace_members')
    .select('user_id, role, workspace_id')
    .eq('id', memberId)
    .single()

  if (!target) return { error: 'Membro não encontrado.' }

  if (target.user_id === currentUserId) {
    return { error: 'Você não pode remover a si mesmo.' }
  }

  // Prevent removing the last admin
  if (target.role === 'admin') {
    const { count } = await admin
      .from('workspace_members')
      .select('id', { count: 'exact', head: true })
      .eq('workspace_id', target.workspace_id)
      .eq('role', 'admin')
      .eq('status', 'active')

    if ((count ?? 0) <= 1) {
      return { error: 'Não é possível remover o último admin do workspace.' }
    }
  }

  const { error } = await admin
    .from('workspace_members')
    .delete()
    .eq('id', memberId)

  if (error) return { error: 'Erro ao remover membro.' }

  revalidatePath('/settings')
  return {}
}

// ─── Update member role ───────────────────────────────────────────────────────

export async function updateMemberRole(
  memberId: string,
  role: 'admin' | 'member',
  workspaceId: string
): Promise<{ error?: string }> {
  const admin = getSupabaseAdminClient()

  // Prevent downgrading the last admin
  if (role === 'member') {
    const { data: target } = await admin
      .from('workspace_members')
      .select('role')
      .eq('id', memberId)
      .single()

    if (target?.role === 'admin') {
      const { count } = await admin
        .from('workspace_members')
        .select('id', { count: 'exact', head: true })
        .eq('workspace_id', workspaceId)
        .eq('role', 'admin')
        .eq('status', 'active')

      if ((count ?? 0) <= 1) {
        return { error: 'Não é possível rebaixar o último admin do workspace.' }
      }
    }
  }

  const { error } = await admin
    .from('workspace_members')
    .update({ role })
    .eq('id', memberId)

  if (error) return { error: 'Erro ao atualizar papel.' }

  revalidatePath('/settings')
  return {}
}
